version: '2'
services:
  rails:
    restart: always
    tty: true
    build: .
    environment:
      - TZ=Asia/Shanghai
      - RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/app
